[project]
name = "gwenlake"
version = "0.4.1"
description = "Gwenlake framework"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE.txt" }

[tool.black]
target-version = ['py36']
exclude = '.*\.ipynb'

[tool.isort]
py_version = 36
include_trailing_comma = "true"
line_length = 88
multi_line_output = 3
